### ISSUE TITLE
IOS Example no longer working

### ISSUE THREAD

**Issue by machinemarine** [m-lab/ndt7-client-ios#57]
This did work but appears to be failing now, for the life of me I can't figure out why. tried with 12.4 and 13.0 simulators but it fails to show download elapsed time and speed, while upload works ok. only difference I could see in debug logs is the download using Operation Queue and upload using Dispatch Queue. I'm very much a novice so no idea if this matters.

examples:

[ndt7] [Operation queue: com.apple.main-thread-thread] [NDT7Test.swift-message(webSocket:message:):407] (info) Download test elapsed: -, TCP info: "-", APP info: "num bytes: 78026285", BBR info: "-"

[ndt7] [Dispatch queue: net.measurementlab.NDT7.upload.test-thread] [NDT7Test.swift-uploadMessage(socket:t0:t1:count:):331] (info) Upload test elapsed: 0.2500019073486328, TCP info: "-", APP info: "num bytes: 212992", BBR info: "-"

**Comment by machinemarine** [comment]
🤔

**Comment by pboothe** [comment]
Huh. This code was not originally developed by M-Lab, but it is our problem that it is not working.

**Comment by miguelcatalinalabs** [comment]
Hi @machinemarine , the issue was already fixed, but we have the version still in Beta and I hope we can have a final version soon.

Thanks

**Comment by miguelangelnet** [comment]
fixed after change the payload logic
