### ISSUE TITLE
Update locate to new API V2 url

### ISSUE THREAD

**Issue by mattcat10** [m-lab/ndt7-client-ios#75]
The ndt7 test is is going to start requiring access tokens from the new v2 locate API . The client will need to be updated 
https://www.measurementlab.net/blog/ndt7-access-tokens/

https://www.measurementlab.net/develop/locate-v2/

**Comment by stephen-soltesz** [comment]
We've rolled back the [access token requirement][1] until this repo is updated to support the Locate v2 API natively.

[1]: https://github.com/m-lab/k8s-support/releases/tag/v2.21.2

**Comment by tmkinger** [comment]
Thanks, it's working now. Once the access token requirement is included again, will there be any changes needed from the client side? 
Or a pod update?

**Comment by pettyalex** [comment]
We already had a private fork of this that's been updated to the Locate V2 API, we'll try and get it merged back into this. PR #77

**Comment by stephen-soltesz** [comment]
Fixed by https://github.com/m-lab/ndt7-client-ios/pull/80
