### ISSUE TITLE
iOS Example not working

### ISSUE THREAD

**Issue by tmkinger** [m-lab/ndt7-client-ios#76]
<img width="487" alt="Screenshot 2020-11-09 at 2 24 41 PM" src="https://user-images.githubusercontent.com/2429619/98519821-4ea87100-2297-11eb-8e7e-45ea81b03b17.png">
Hi,

The iOS example has not been working since last week. It was perfectly fine earlier.
I get the following error now as soon as I start the test -

"Mlab server ndt-iupui-mlab1-maa01.mlab-oti.measurement-lab.org has an error during test"

**Comment by stephen-soltesz** [comment]
We've rolled back the [access token requirement][1] until this repo is updated to support the Locate v2 API natively. The error should resolve over the next 12hrs.

[1]: https://github.com/m-lab/k8s-support/releases/tag/v2.21.2

**Comment by tmkinger** [comment]
Thanks, it's working now. Once the access token requirement is included again, will there be any changes needed from the client side?
Or a pod update?

**Comment by stephen-soltesz** [comment]
There's a PR in the works to add the new functionality needed for access tokens. Without being familiar with iOS to know if there are additional steps, at least I imagine clients would need to be recompiled with the new library to bring in the new functionality.

**Comment by tmkinger** [comment]
Hi,
This issue has been happening again from the last week or more.
Are there any changes required in the iOS project to fix this?

**Comment by stephen-soltesz** [comment]
Please adapt your client to use the code like that in https://github.com/m-lab/ndt7-client-ios/pull/77 The Locate v2 API is now required.

The android and ios clients for ndt7 are community supported & maintained. Any contributions you make would be welcome.

**Comment by tmkinger** [comment]
Thanks for your response @stephen-soltesz!
I use the library via Cocoapods, so will I have to wait for the changes to be pushed to production for me to be able to make these changes after a pod update?

**Comment by stephen-soltesz** [comment]
This is the Cocoapod? https://cocoapods.org/pods/NDT7

@miguelangelnet is probably the only one with write access to that pod.
