### ISSUE TITLE
iOS Example Not Working

### ISSUE THREAD

**Issue by tmkinger** [m-lab/ndt7-client-ios#79]
Hi,
The iOS example has not been working since last week. It was perfectly fine earlier.
I get the following error now as soon as I start the test -

"Mlab server ndt-iupui-mlab1-maa01.mlab-oti.measurement-lab.org has an error during test"
<img width="479" alt="Screenshot 2021-02-09 at 10 58 45 AM" src="https://user-images.githubusercontent.com/2429619/107320025-e5b6dc00-6ac5-11eb-93ed-e06cfc5402a5.png">

There was a similar issue raised last year #76.
Is there any change needed to be made from my iOS project now ?

**Comment by stephen-soltesz** [comment]
The Locate v2 API is now required for ndt7 clients. There are pending changes in https://github.com/m-lab/ndt7-client-ios/pull/77 to add Locate v2 API support to the ios client.

The android and ios clients for ndt7 are community supported & maintained. Unfortunately, this means that support is limited. If you are able to provide code contributions to PR#77 they would be welcome.

**Comment by olgagalchenko** [comment]
This should be fixed now! https://github.com/m-lab/ndt7-client-ios/pull/80

**Comment by stephen-soltesz** [comment]
@tmkinger would you try again using the changes recently added by https://github.com/m-lab/ndt7-client-ios/pull/80 ?
